"""add_rating_columns_to_characters_films_starships

Revision ID: 6c61c9cdb35d
Revises: 3d8fd48315c3
Create Date: 2025-07-20 18:14:06.936567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c61c9cdb35d'
down_revision: Union[str, Sequence[str], None] = '3d8fd48315c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('characters', sa.Column('rating_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'rating_count')
    op.drop_column('characters', 'rating')
    # ### end Alembic commands ###
